application_api_version: v1beta1
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  image:
    type: string
    default: gcr.io/block-inc-tbd-public/dwn-server:0.0.1
    x-google-marketplace:
      type: IMAGE
      image:
        generatedProperties:
          splitByColon:
            before: repository
            after: tag
required:
- name
- namespace
- image
